env:
  browser: true
  es2021: true
ignorePatterns: []
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: [
    "./src/tsconfig.json",
  ]
plugins:
  - '@typescript-eslint'
rules:
  semi: [error, always]
  quotes: [error, single]
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-unused-vars": off
  "@typescript-eslint/no-floating-promises": error
  "@typescript-eslint/no-explicit-any": off